version: 2
jobs:
  build:
    environment:
      CI_ENV: "CircleCI"
      PROJECT_NAME: "share_my_desk"

    parallelism: 1

    docker:
      - image: circleci/node:10.12.0

    steps:
      - checkout

      - run:
          name: Instantiate npm configs
          command: |
              echo "Setting up required npm config"
              npm config set share-my-desk:ORG_EMAIL_DOMAIN example.com
              npm config set share-my-desk:JWT_SECRET $0M3_S3cr37_VAiu3
      
      - restore_cache:
          key: node_modules_cache-{{ checksum "package.json" }}

      - run: npm install

      - run:
          name: Jest Test
          command: npm test

      - save_cache:
          key: node_modules_cache-{{ checksum "package.json" }}
          paths:
            - node_modules
